### ISSUE TITLE
Static Library targets

### ISSUE THREAD

**Issue by lighth7015** [Zirias/zimk#2]
So can I build an entirely static library with zimk?

**Comment by Zirias** [comment]
The documentation really needs to be fixed, didn't touch it for years :(

Yes, you can. The default (`all`) target builds everything, which includes the shared libs. To build the static libs, use the `staticlibs` target, to install them use `installstaticlibs`.

**Comment by lighth7015** [comment]
Yeah, I just noticed I need _in my application_'s rules, my library needs to be listed in both  `_STATICLIBS` and `_STATICDEPS`. Still an awesome build system, though!

I have nearly a dozen improvements, I can submit requests/issues for, if you wouldn't mind working with me to get them implemented. :D

**Comment by Zirias** [comment]
Oh boy, I had no time for this *in years* and now I see I didn't close this one.

I'm recently trying to modernize it and add more features, which only makes the issue of missing docs worse, but then, this is a different issue ... so closing this one here.
