### ISSUE TITLE
Doesn't build on macOS - "missing separator" in zimk.mk line 9

### ISSUE THREAD

**Issue by bferguson3** [Zirias/zimk#3]

**Comment by Zirias** [comment]
line 9 in `zimk.mk` is an `undefine` statement. AFAIK, older versions of GNU make don't support it. Can you upgrade your GNU make tool?

**Comment by bferguson3** [comment]
You're right, my path wasn't finding the right version of make. However it still fails:

directory not found for option '-Llib/x86_64-apple-darwin20.3.0/release'

Is there a way to not force it to look for a folder with the uname? This seems like it would only work on certain distros.

**Comment by Zirias** [comment]
This is for libraries that are built *as part of the project*, so the build should create it. Can you tell me which project you are trying to build? Any other output (with adding `V=1` to the `make` command)?

**Comment by bferguson3** [comment]
Sure - this is for mkd64. (I built it only a few days ago on Raspberry Pi)

cc -obin/x86_64-apple-darwin20.3.0/release/mkd64 -Wl,-E  -Llib/x86_64-apple-darwin20.3.0/release obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/mkd64.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/image.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/track.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/block.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/defalloc.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/filemap.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/diskfile.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/cmdline.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/modrepo.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/util.o obj/x86_64-apple-darwin20.3.0/release/src/bin/mkd64/platformutil_posix.o 
ld: warning: directory not found for option '-Llib/x86_64-apple-darwin20.3.0/release'
ld: unknown option: -E
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [src/bin/mkd64/mkd64.mk:14: bin/x86_64-apple-darwin20.3.0/release/mkd64] Error 1

It could be macOS pathing not finding the correct linker, but I can't quite figure it out.

**Comment by Zirias** [comment]
Uh. Well, then the issue should probably be with `mkd64`, although I'm not entirely sure about that. I don't own any apple system. So I can only give some rough hints: It's interesting that `ld` complains about `-E`. This option is used to export symbols from the main binary (and works on Linux and FreeBSD). The exports are necessary for the plugins used with `mkd64` to work. I *assume* the error about `-L` is just a red herring. Normally, linking ignores any paths for `-L` that are not found…

Just as an additional hint, I probably won't maintain `mkd64` any more. I started a replacement with a library [lib1541img](https://github.com/excess-c64/lib1541img) and a GUI using it, [v1541commander](https://github.com/excess-c64/v1541commander). Unfortunately, there's no commandline tool yet (and I'm unsure whether these will build on MacOS).

**Comment by bferguson3** [comment]
Thanks anyway then. I need a cli tool. I'll just make my own that will be
fully cross platform.

**Comment by Zirias** [comment]
If you want to do that, you *could* still have a look at the library, might save you a lot of work!

Apart from that, `mkd64` code *is* cross-platform, but unfortunately, a "plugin mechanism" is not. But then, it's most likely just fiddling with compiler/linker settings to get it to work :)

**Comment by bferguson3** [comment]
I've been fiddling for two days. If you don't support it, I'm better off on my own. Thanks though

**Comment by Zirias** [comment]
* I don't support `mkd64` because I already have [lib1541img](https://github.com/excess-c64/lib1541img) offering the same functionality (plus more and also bugs fixed). That's why I said if you want to create your own CLI tool, you might want to have a look, using the lib will save you most of the work. Actually, a CLI tool using it is on my TODO-list (whenever I have time)
* I don't explicitly support Mac, because there's no way for me to test. My code is portable and typically tested with Linux, FreeBSD and Windows, and there's no reason it shouldn't work on Mac, but building it correctly might be a different story. I'll happily accept pull requests fixing things on Mac.
